from construct import BitStruct, BitsSwapped, Flag  # type: ignore

_EMPTY_FLAG = ""

# We will use a bitstruct with 64 bits instead of the widebits implementation in serum-js.
ACCOUNT_FLAGS_LAYOUT = BitsSwapped(  # Swap to little endian
    BitStruct(
        "initialized" / Flag,
        "market" / Flag,
        "openOrders" / Flag,
        "requestQueue" / Flag,
        "eventQueue" / Flag,
        "bids" / Flag,
        "asks" / Flag,
        _EMPTY_FLAG / Flag,  # XXX: I can't get Padding to work correctly.
        _EMPTY_FLAG / Flag,
        _EMPTY_FLAG / Flag,
        _EMPTY_FLAG / Flag,
        _EMPTY_FLAG / Flag,
        _EMPTY_FLAG / Flag,
        _EMPTY_FLAG / Flag,
        _EMPTY_FLAG / Flag,
        _EMPTY_FLAG / Flag,
        _EMPTY_FLAG / Flag,
        _EMPTY_FLAG / Flag,
        _EMPTY_FLAG / Flag,
        _EMPTY_FLAG / Flag,
        _EMPTY_FLAG / Flag,
        _EMPTY_FLAG / Flag,
        _EMPTY_FLAG / Flag,
        _EMPTY_FLAG / Flag,
        _EMPTY_FLAG / Flag,
        _EMPTY_FLAG / Flag,
        _EMPTY_FLAG / Flag,
        _EMPTY_FLAG / Flag,
        _EMPTY_FLAG / Flag,
        _EMPTY_FLAG / Flag,
        _EMPTY_FLAG / Flag,
        _EMPTY_FLAG / Flag,
        _EMPTY_FLAG / Flag,
        _EMPTY_FLAG / Flag,
        _EMPTY_FLAG / Flag,
        _EMPTY_FLAG / Flag,
        _EMPTY_FLAG / Flag,
        _EMPTY_FLAG / Flag,
        _EMPTY_FLAG / Flag,
        _EMPTY_FLAG / Flag,
        _EMPTY_FLAG / Flag,
        _EMPTY_FLAG / Flag,
        _EMPTY_FLAG / Flag,
        _EMPTY_FLAG / Flag,
        _EMPTY_FLAG / Flag,
        _EMPTY_FLAG / Flag,
        _EMPTY_FLAG / Flag,
        _EMPTY_FLAG / Flag,
        _EMPTY_FLAG / Flag,
        _EMPTY_FLAG / Flag,
        _EMPTY_FLAG / Flag,
        _EMPTY_FLAG / Flag,
        _EMPTY_FLAG / Flag,
        _EMPTY_FLAG / Flag,
        _EMPTY_FLAG / Flag,
        _EMPTY_FLAG / Flag,
        _EMPTY_FLAG / Flag,
        _EMPTY_FLAG / Flag,
        _EMPTY_FLAG / Flag,
        _EMPTY_FLAG / Flag,
        _EMPTY_FLAG / Flag,
        _EMPTY_FLAG / Flag,
        _EMPTY_FLAG / Flag,
        _EMPTY_FLAG / Flag,
    )
)
